// remote-front-end/air-asia-app/src/app/components/time-table/time-table.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Observable } 				from 'rxjs/Observable';

import { AbstractComponent } 		from '../../../magnolia-app/component/abstract.component';
import { TrainService } 			from '../../services/train.service';

@Component({
  selector: '[app-time-table]',
  templateUrl: './time-table.component.html',
  styleUrls: ['./time-table.component.css']
})
export class TimeTableComponent extends AbstractComponent {
	/** List of trains. */
	trains: Observable<any[]>;
	/** Interval. */
	interval: any;

	/**
	 * Constructor
	 */
	constructor(private trainService: TrainService) {
		super();
	}
	
	/**
	 * On init
	 */
  	ngOnInit() {
  		super.ngOnInit();
  		
  		//Loads a first time
  		this.loadTrains()
  		
  		//Then loads every 5 seconds
  		this.interval = setInterval(() => {
  		    this.loadTrains(); 
  		}, 5000);
  	}
  	  	
	/**
	 * On destroy
	 */
  	ngOnDestroy() {
		if (this.interval) {
		    clearInterval(this.interval);
		}
  	}
  	
  	/**
  	 * Loads the trains from Magnolia
  	 */
  	private loadTrains() {
  		this.trainService.getTrains().subscribe(data => {
  			this.trains = data.results;
  		});
  	}
}
<table class="mgn-train-time-table" cellspacing="0">
<tr>
	<ng-template ngFor let-column [ngForOf]="component.selectColumns">
	<th *ngIf="column === 'departStation'" style="width: 208px;">Dep. station</th>
	<th *ngIf="column === 'arrivalStation'" style="width: 208px;">Arr. station</th>
	<th *ngIf="column === 'departure'" style="width: 167px;">Dep. time</th>
	<th *ngIf="column === 'arrival'" style="width: 167px;">Arr. time</th>
	<th *ngIf="column === 'length'" style="width: 73px;">Length</th>
	<th *ngIf="column === 'stops'" style="width: 72px;">Num stops</th>
	<th *ngIf="column === 'type'" style="width: 78px;">Type</th>
	<th *ngIf="column === 'price'" style="width: 217px;">Price</th>
	<th *ngIf="column === 'flexPrice'" style="width: 125px;">Flex price</th>
	</ng-template>
</tr>
<tr *ngFor="let train of trains" class="firstrow">
	<ng-template ngFor let-column [ngForOf]="component.selectColumns">
	<td *ngIf="column === 'departStation'" style="width: 208px;">{{train.from}}</td>
	<td *ngIf="column === 'arrivalStation'" style="width: 208px;">{{train.to}}</td>
	<td *ngIf="column === 'departure'" style="width: 167px;">{{train.start}}</td>
	<td *ngIf="column === 'arrival'" style="width: 167px;">{{train.end}}</td>
	<td *ngIf="column === 'length'">{{train.length}}</td>
	<td *ngIf="column === 'stops'">{{train.numStops}}</td>
	<td *ngIf="column === 'type'">{{train.type}}</td>
	<td *ngIf="column === 'price'">{{train.price}}</td>
	<td *ngIf="column === 'flexPrice'">{{train.flexPrice}}</td>
	</ng-template>
</tr>
</table>

// remote-front-end/react-app/src/app/component/TimeTable.js
import React from 'react';

import AbstractComponent from "../magnolia/AbstractComponent"
import axios from 'axios';

import ENVIRONMENT from "../../environments/environment"

class TimeTable extends AbstractComponent {
	
	/**
	 * On init
	 */
	constructor(props) {
		super(props);
		this.state = {
			trains: []
		};
	}
	
	/**
	 * Once rendered
	 */
	componentDidMount() {
		super.componentDidMount();
		
		let component = this;
		
		// Load the trains for the first time
		this.fetchTrainsData(component);
		
		// Then trigger an uodate every 5 seconds
		setInterval(function() {
			component.fetchTrainsData(component);
		}, 5000);

	}
	
	/**
	 * Fetch the trains data
	 */
	fetchTrainsData(component) {
		axios
			.get(ENVIRONMENT.trainRestUrl)
			.then(response => {
				component.setState( {trains: response.data.results} );
				console.log("Train loaded");
			}).catch(error => {
			    console.log(error);
			});		
	}
	
	renderTrain(train, rowIndex) {
		var cells = [];

		if (this.props.component.selectColumns!=null) {
			this.props.component.selectColumns.forEach(function(selectedColumn) {
				if (selectedColumn === 'departStation') {
					cells.push(<td key={selectedColumn}>{train.from}</td>);
				}
				if (selectedColumn === 'arrivalStation') {
					cells.push(<td key={selectedColumn}>{train.to}</td>);
				}
				if (selectedColumn === 'departure') {
					cells.push(<td key={selectedColumn}>{train.start}</td>);
				}
				if (selectedColumn === 'arrival') {
					cells.push(<td key={selectedColumn}>{train.end}</td>);
				}
				if (selectedColumn === 'length') {
					cells.push(<td key={selectedColumn}>{train.length}</td>);
				}
				if (selectedColumn === 'stops') {
					cells.push(<td key={selectedColumn}>{train.numStops}</td>);
				}
				if (selectedColumn === 'type') {
					cells.push(<td key={selectedColumn}>{train.type}</td>);
				}
				if (selectedColumn === 'price') {
					cells.push(<td key={selectedColumn}>{train.price}</td>);
				}
				if (selectedColumn === 'flexPrice') {
					cells.push(<td key={selectedColumn}>{train.flexPrice}</td>);
				}
			})
		}

		return cells;
	}
	
	/**
	 * Render the element
	 */
	render() {
		const trains = this.state.trains;

		return (
			<table className="mgn-train-time-table" cellSpacing="0">
			<tbody>
				<tr>
					{
						this.props.component.selectColumns.map((selectColumn, index) => (
							<th key={index}>{selectColumn}</th>	
						))
					}
				</tr>			
				
				{
					trains.map((train, index) => (
						<tr key={index}>{this.renderTrain(train, index)}</tr>
					))
				}
				
			</tbody>
			</table>
	    );
	}
}

export default TimeTable;
