// remote-front-end/react-app/src/app/component/Header.js
import React, { Component } from 'react';

import ENVIRONMENT from "../../environments/environment"

class Header extends Component {
	render() {
	    let logo = ENVIRONMENT.staticFilePath + "/img/logo-magnolia.svg";
	    
		return (
	    	<nav className="navbar navbar-default mgn-train-header">
				<div className="container">
					<div className="navbar-header">
						<button className="navbar-toggle collapsed" type="button" data-target="#menu-main-dropdown-mobile" data-toggle="collapse">
							<span className="icon-bar"></span> 
							<span className="icon-bar"></span> 
							<span className="icon-bar"></span>
						</button>
						<a className="navbar-brand" href="index.html"> 
							<img width="120px" className="img-responsive" src={logo} alt=""/>
						</a>
					</div>
					
				    <div className="collapse navbar-collapse">
				      <ul className="nav navbar-nav">
				          <li><a>Home</a></li>
				          <li><a>Contact</a></li>
				          <li><a>Sitemap</a></li>
				          <li><a>Login</a></li>
				      </ul>
				    </div>
				</div>	
			</nav>
	    );
	}
}

export default Header;

// angular-concept-webapp/src/main/webapp/modules/angular-standalone/webresources/angular-app/src/app/components/header/header.component.ts
import { Component, OnInit } 	from '@angular/core';

import { environment } 			from '../../../environments/environment';

@Component({
  selector: '.mgn-train-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {
	id: string;
	env: any;

  	constructor() {
  		this.env = environment;
  	}

  	ngOnInit() {
  	}
}
<div class="container">
	<div class="navbar-header">
		<button class="navbar-toggle collapsed" type="button" data-target="#menu-main-dropdown-mobile" data-toggle="collapse">
			<span class="icon-bar"></span> 
			<span class="icon-bar"></span> 
			<span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="index.html"> 
			<img width="120px" class="img-responsive" src="{{env.staticFilePath}}/assets/img/logo-magnolia.svg">
		</a>
	</div>
	
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
          <li><a href="#">Home</a></li>
          <li><a href="#">Contact</a></li>
          <li><a href="#">Sitemap</a></li>
          <li><a href="#">Login</a></li>
      </ul>
    </div>
</div>
